[package]
name = "nds"
version = "0.1.0"
authors = ["BlueTheDuck <pedroignacioperezvargas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nds-sys = { path = "nds-sys" }
nds-proc-macros = { path = "nds-proc-macros" }
bitflags = "^1.3"
paste = "^1.0"
lazy_static = { version = "^1.4", features = [ "spin_no_std" ], optional = true }
spin = { version = "^0.9", default-features = false, features = [ "spin_mutex" ] , optional = true }

[workspace]
members = [ "nds-sys", "nds-proc-macros", "libc" ]

[features]
default = [ "default_panic_screen", "nocash_tty" ]
default_panic_screen = []
nocash_tty = [ "spin", "lazy_static" ]
