[package]
name = "nds"
version = "0.1.0"
authors = ["BlueTheDuck <pedroignacioperezvargas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nds-sys = { path = "nds-sys" }
nds-entry = { path = "nds-entry" }
bitflags = "*"
paste = "*"
lazy_static = { version = "*", features = ["spin_no_std"] }
spin = { version = "*" }

[workspace]
members = [ "nds-sys", "nds-entry", "libc" ]