[build]
target = "armv5te-none-eabi"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.armv5te-none-eabi]
runner = "melonDS"
rustflags = [
    "--cfg", "portable_atomic_unsafe_assume_single_core",
    "-Clink-arg=-specs=ds_arm9.specs",
    "-Ctarget-cpu=arm946e-s",
    
    # link sysbase and the C library
    "-Clink-args=-Wl,--start-group -lc -Wl,--end-group",

    # Some debugging flags
    "-Clink-arg=-Wl,-Map=target/nds.map",
    # "-Clink-arg=-Wl,--verbose",
    # "--print", "link-args"
]
linker = "arm-none-eabi-gcc"
