name: rustdoc
on:
  push:
   branches:
   - master

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: ""
  RUSTUP_MAX_RETRIES: 10
  DEVKITPRO: "/opt/devkitpro"
  DEVKITARM: "/opt/devkitpro/devkitARM"

jobs:
  rustdoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install devkitPro
      shell: bash
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends apt-utils
        sudo apt-get install -y --no-install-recommends sudo ca-certificates pkg-config curl wget bzip2 xz-utils make bsdtar doxygen gnupg
        sudo apt-get install -y --no-install-recommends gdebi-core apt-utils
        wget https://github.com/devkitPro/pacman/releases/latest/download/devkitpro-pacman.amd64.deb && sudo gdebi -n devkitpro-pacman.amd64.deb && rm devkitpro-pacman.amd64.deb
        yes | sudo dkp-pacman -Scc
        sudo dkp-pacman -Sy
        sudo dkp-pacman -Syu
        sudo dkp-pacman -S --noconfirm nds-dev


    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt, rust-src

    - name: Build Documentation
      run: cargo doc --no-deps --quiet --workspace

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
