name: rustdoc
on:
  push:
   branches:
   - master

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: ""
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install required packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gcc build-essential


    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt, rust-src
      
    - name: Build Documentation
      run: cargo doc --all-features --no-deps --workspace
      
      
    - name: Create an index.html page
      run: echo "<meta http-equiv="refresh" content="0; URL=armv5te-nintendo-ds-newlibeabi/doc/nds_rs/index.html" />" >> ./target/armv5te-nintendo-ds-newlibeabi/doc/index.html
      
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/armv5te-nintendo-ds-newlibeabi/doc
        force_orphan: true
